title: OneLaw Cloud API
email: support@onelaw.co.nz
description: >-
  Official documentation for the OneLaw Cloud API.

url: "https://www.onelaw.co.nz"

remote_theme: just-the-docs/just-the-docs

author: OneLaw Integration Team

github_username: onelawcloud
linkedin: company/onelaw-limited

timezone: Pacific/Auckland

just_the_docs:
  logo: "assets/images/onelaw.png"
  favicon_ico: "assets/images/favicon.avif"
  color_scheme: light
  navigation_depth: 3
  aux_links:
    "OneLaw Website":
      - "https://www.onelaw.co.nz"
    "Support":
      - "mailto:support@onelaw.co.nz"
